title: "Eduard Keilmann"
author: "Eduard Keilmann"
description: "Astrophysics research at the University of Cologne"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"


# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header
mathjax: true

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  # - {file: "index.html"}
  - {url: "https://eduard-keilmann.github.io/research/", title: "Research interests"}
  - {url: "https://eduard-keilmann.github.io/publications/", title: "Publications"}
  - {file: "CV_Lebenslauf_research_Englisch.pdf", title: "CV"}
  - {url: "https://eduard-keilmann.github.io/about/", title: "About me"}
  #- {file: "tutorial.html", title: "tutorial of this theme"}
  #- {file: "README.md", title: "Installation Guide of this theme"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:keilmann@ph1.uni-koeln.de"}
  - {title: NASA ADS, icon: atom, url: "https://ui.adsabs.harvard.edu/public-libraries/RGi-dPyyQlq1n4eZFpzLAw"}
  - {title: ORCID, icon: orcid, url: "https://orcid.org/0000-0003-1735-2021"}
  - {title: Scopus, icon: database, url: "https://www.scopus.com/authid/detail.uri?authorId=57211265590"}
  - {title: LinkedIn, icon: linkedin, url: "https://de.linkedin.com/in/eduard-keilmann-a0b35b281"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}
  - {title: Impressum, url: "https://eduard-keilmann.github.io/impressum/"}
  - {title: Sitemap, url: "https://eduard-keilmann.github.io/sitemap.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-sitemap
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-robots-txt
 - jekyll-ping-google
 - jekyll-include-cache
 

url: "https://eduard-keilmann.github.io"
seo:
  name: "Dr. Eduard Keilmann"
  description: "Astrophysics/Astronomy Researcher, Physicist, Postdoc"

google_analytics: "G-DBSEPX57EW"
